### ISSUE TITLE
Sum / Product do not work in zsh

### ISSUE THREAD

**Issue by nigelgbanks** [mikeplus64/fun.sh#2]
``` sh
~ list {1..20} | product
foldl:4: command not found: lambda a b . echo $(($a * $b))
...
```

zsh 5.0.2 (x86_64-apple-darwin13.0)

**Comment by Shadowhunter2e** [comment]
have you tried #!/bin/sh

**Comment by nigelgbanks** [comment]
Oh I forgot about this, no I haven't as I was mostly interested in using it in the prompt rather than in a script.
